config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.10
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/dnorcini/ChicagoCCDSim:
      branch: master
      repo: https://github.com/dnorcini/ChicagoCCDSim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/dnorcini/ChicagoCCDSim git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-eggplant-rottweiler.sh
        container: qc.acc_snippy-blue-dalmatian
  QC.Doc:
    repos:
      github.com/dnorcini/ChicagoCCDSim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-platinum-cuscus.sh
        container: qc.doc_boozy-gamboge-duck
      github.com/dnorcini/ChicagoCCDSim git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-teal-shrew.sh
        container: qc.doc_woolly-alizarin-jaguar
      github.com/dnorcini/ChicagoCCDSim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-salmon-spaniel.sh
        container: qc.doc_scummy-chocolate-moth
  QC.Lic:
    repos:
      github.com/dnorcini/ChicagoCCDSim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-lavender-serval.sh
        container: qc.lic_stuffy-crimson-starfish
  QC.Ver:
    repos:
      github.com/dnorcini/ChicagoCCDSim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-cream-chinchilla.sh
        container: qc.ver_sleazy-myrtle-mule
timeout: 5400
